services:
  lsp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./workspaces:/workspaces
    environment:
      - PYTHONPATH=/app
      - WORKSPACE_DIR=/workspaces