apiVersion: v1
kind: Service
metadata:
  name: mastermind-smart-suggestions-service
spec:
  selector:
    app: mastermind-smart-suggestions
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
  type: LoadBalancer
