name: Deploy to GKE

on:
  push:
    branches:
      - dev_lsp_implementation

jobs: 
  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.DEV_GCP_CREDENTIALS }}'

      - name: Login to Google Container Registry (GCR)
        uses: docker/login-action@v3
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.DEV_GCP_CREDENTIALS }} 

      - name: Build and Push Docker Image
        run: |
          export PROJECT_ID=demopostrecruitmentjoinin-fkyn
          export IMAGE_TAG=${{ github.run_id }}
          export IMAGE=gcr.io/$PROJECT_ID/mastermind-suggestion:$IMAGE_TAG
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ACTIONS_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Manually clone k8s-migrations repository
        run: |
          git clone --branch main git@github.com:berri-bot/k8s-migrations.git k8s-migrations
          cd k8s-migrations
          git branch -r

      - name: Deploy to Kubernetes
        run: |
          export TAG_IMAGE_WORKER=${{ github.run_id }}
          export PROJECT_ID=demopostrecruitmentjoinin-fkyn
          ./k8s-migrations/web/dev/k8s_connect.sh
          ./k8s-migrations/web/dev/mastermind_smart_suggestions/deploy_server.sh