name: Deploy to GKE

on:
  push:
    branches:
      - main 

jobs: 
  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.DEV_GCP_CREDENTIALS }}'

      - name: Login to Google Container Registry (GCR)
        uses: docker/login-action@v3
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.DEV_GCP_CREDENTIALS }} 

      - name: Build and Push Docker Image
        run: |
          export PROJECT_ID=demopostrecruitmentjoinin-fkyn
          export IMAGE_TAG=${{ github.run_id }}
          export IMAGE=gcr.io/$PROJECT_ID/mastermind-smart-suggestions:$IMAGE_TAG

          docker build -t $IMAGE .
          docker push $IMAGE
